### ISSUE TITLE
Rebase command doesn't refresh tree properly.

### ISSUE THREAD

**Issue by sminnee** [brotherbard/gitx#1]
The rebase command had no feedback, I had to press Command-R to know that it had worked. It should refresh the view for you automatically, when it's done.

> I thought it did, I must have broken it somewhere. I'll try to figure out what's wrong.

Test case:
- Go to "All branches" view.
- Create a branch, 'testbranch' from an arbitrary point in your change history
- Checkout that branch
- Commit a junk commit
- Return to the tree view
- Right-click Rebase testbranch starting at master

Expected: the view refreshes to show the new tree.
Actual: the 'testbranch' branch marker disappears, but the tree itself stays the same - in effect, it's left showing an orphaned branch.  Pressing refresh shows the new tree.

It appears that the refresh function you can chosen only moves branch markers and doesn't actually update the tree.

**Comment by brotherbard** [comment]
Bugfix: Update the history view when doing rebase or other commands.

When using All Branches or Local Branches the history view would not be updated if the commnad changed the history.

closed by 82e6fd013c7abc3218cb575f19ff43e42001e26a

**Comment by sminnee** [comment]
I just confirmed this.
