### ISSUE TITLE
search by commit id

### ISSUE THREAD

**Issue by astubbs** [brotherbard/gitx#14]

**Comment by brotherbard** [comment]
You can already do this by selecting "SHA" in the search fields pop up menu.

**Comment by astubbs** [comment]
Awesome! Never noticed.. But why bother having them seperate?

**Comment by brotherbard** [comment]
Not sure, it's been that way from before I started working on it.

**Comment by astubbs** [comment]
IMO I don't see a point in seperating out the three categories from this point of view (versus results view). You don't see spotlight doing that for example.

+1 to take away the categories, and just always search all of them - or, by default search all three, and leave the opportunity to refine the search to one of the categories.

**Comment by hardkrash** [comment]
+1 on removing the separation of searches,  example in mail.app  you can refine the searches with a search bar.... but that is overkill for gitx.

**Comment by brotherbard** [comment]
I removed the separation of the Subject/Author/SHA searches in SHA: 4fad6b60a383463530f3854783e80f7a789a7263
