### ISSUE TITLE
when searching, just jump to result instead of clearing everything

### ISSUE THREAD

**Issue by astubbs** [brotherbard/gitx#16]
Title's a little hard to understand, but when you search currently, ever other commit is hidden, which makes it hard to see the context of the commit.

I don't know how to solve this nicely, but it would be very useful...

**Comment by brotherbard** [comment]
Also, how do you show multiple commits that match the search?

**Comment by astubbs** [comment]
Indeed :/ - perhaps a find/find again kind of thing?

**Comment by brotherbard** [comment]
I implemented a find type search in SHA: 4fad6b60a383463530f3854783e80f7a789a7263
