### ISSUE TITLE
Push and Pull buttons aren't updated when you switch branch.

### ISSUE THREAD

**Issue by sminnee** [brotherbard/gitx#2]
If you switch to a new branch within GitX, the "pull" and "push" buttons on the toolbar are still linked to the branch you were originally on.

Here's a test case. Substitute mybranch for a branch that you actually have on a repository.
- checkout branch mybranch on the commandline
- start gitx
- right click the master branch bubble on commit tree, and select 'checkout master'
- click and hold pull
- Expected: "Pull to master from:"
- Actual: "Pull to mybranch from:"

**Comment by sminnee** [comment]
I've tried out 3616fd3119feeec6d38010f1de8f39d8c59e0044 - when you switch branch and press-and-hold the pull menu, it still says "Pull to (oldbranch) from:"

**Comment by brotherbard** [comment]
I can't get it to fail anymore. Can you make sure you rebuilt with the changes? 
line 32 of PBGitRepository.m should be [self updateBranchMenus];
Then (in Xcode) click and hold the Build toolbar item and select Clean All, then build and run GitX again.

**Comment by sminnee** [comment]
Weird, I thought I did that, but it seems to work now.

Keep up the good work - it's really exciting to see all these new features in GitX! :-)

I can't seem to close this issue, but I can confirm it's fixed.

**Comment by brotherbard** [comment]
Thank you for confirming it.
