### ISSUE TITLE
Exception thrown when starting gitx from directory with no git repo

### ISSUE THREAD

**Issue by kenliu** [brotherbard/gitx#21]
Error message:

> 2010-04-21 13:50:20.751 gitx[14048:903] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '[NOTE: this exception originated in the server.]
> working directory doesn't exist.'

**Comment by brotherbard** [comment]
This should be fixed in SHA: 92a44542ae8990b1fb69a270bf2884c760d12dc7
