### ISSUE TITLE
Offical repo?

### ISSUE THREAD

**Issue by raulriera** [brotherbard/gitx#22]
This repo is waaaaay more advanced that the "official one", I was wondering if the official one was abandoned... I have zero knowledge of compiling applications, any help with compiling this code will be appreciated...

Sorry that this is not "an issue" but there is not a real place for questions here

**Comment by godDLL** [comment]
Get your binaries at [github.com/brotherbard/gitx/downloads](http://github.com/brotherbard/gitx/downloads)
Send an e-mail to the [repo owner](http://github.com/brotherbard) if you have questions.

**Comment by raulriera** [comment]
Thanks!

**Comment by avit** [comment]
It's also easy to build the latest yourself.
- Clone this fork
- Open the GitX.xcodeproj file in XCode
- Hit Build from the Build menu
- Compiled files show up in the 'build' folder.
