### ISSUE TITLE
Git pull on branches/master does a git fetch only

### ISSUE THREAD

**Issue by hako74** [brotherbard/gitx#23]
It happened to me and a collegea and I was abble to reproduce this.  
- refresh the commit list  
- right click master and choose "pull origin and update master"  
- refresh the GUI and then try pulling again, I'm up-to-date according to Gitx  
- enter the console (by terminal button), execute git pull  
- again I get an update, after that all is fine.  
  [update]  
  Performing the same action by right-clicking the Remotes --> Origin, the local Master branch is updated correctly.  
  We lost some changes because of this bug.

**Comment by 0x3333** [comment]
This is because you have to execute a git pull only, isn't it?

**Comment by hako74** [comment]
I am talking about the behaviour of pulling in GitX when rightclicking on Branches / Remotes. 
Git pull origin = git fetch origin + git merge origin

**Comment by hako74** [comment]
I do have an update:
The behaviour of the option "pull origin and update master" when you right click "BRANCHES/master" seems to be doing a "git fetch" instead of a "git pull". 

The changes we lost were because a collegae hit "git revert" while in the middle of a merge conflict.

**Comment by brotherbard** [comment]
I don't see any code path where the pull command would do a fetch instead.
