### ISSUE TITLE
Running GitX from terminal causes uncaught exception

### ISSUE THREAD

**Issue by dmilith** [brotherbard/gitx#25]
deldagorin:[dmilith:~ ]:(12:39) → GitX
2010-05-04 12:39:48.196 GitX[69551:903] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '[NOTE: this exception originated in the server.]
working directory doesn't exist.'
**\* Call stack at first throw:
(
 0   CoreFoundation                      0x94e52bda **raiseError + 410
 1   libobjc.A.dylib                     0x95fa4509 objc_exception_throw + 56
 2   Foundation                          0x94f68e70 -[NSConnection sendInvocation:internal:] + 4161
 3   Foundation                          0x94f67ca9 -[NSDistantObject forwardInvocation:] + 411
 4   CoreFoundation                      0x94df98a4 ___forwarding_** + 1108
 5   CoreFoundation                      0x94df93d2 _CF_forwarding_prep_0 + 50
 6   GitX                                0x00002f31 main + 797
 7   GitX                                0x000019f1 start + 53
)

**Comment by dmilith** [comment]
without IDIOTIC formatting: http://pastie.org/944946

**Comment by lucksus** [comment]
same problem here running the 'GitX_3-22-2010.zip' snapshot on OS 10.6.4.

lucksus:Resources nico$ pwd
/Applications/GitX.app/Contents/Resources
lucksus:Resources nico$ gitx
2010-06-22 15:34:02.723 gitx[3535:903] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '[NOTE: this exception originated in the server.]
working directory doesn't exist.'
**\* Call stack at first throw:
(
    0   CoreFoundation                      0x90ceebba **raiseError + 410
    1   libobjc.A.dylib                     0x98394509 objc_exception_throw + 56
    2   Foundation                          0x931dfe68 -[NSConnection sendInvocation:internal:] + 4161
    3   Foundation                          0x931deca1 -[NSDistantObject forwardInvocation:] + 411
    4   CoreFoundation                      0x90c95884 ___forwarding_** + 1108
    5   CoreFoundation                      0x90c953b2 _CF_forwarding_prep_0 + 50
    6   gitx                                0x00003ea1 main + 797
    7   gitx                                0x0000293e start + 54
)
Trace/BPT trap
lucksus:Resources nico$

**Comment by lucksus** [comment]
I have the same problem even with the GitX 0.7 stable snapshot. However the stable repository's head is working fine..

**Comment by brotherbard** [comment]
This should be fixed in SHA: 92a44542ae8990b1fb69a270bf2884c760d12dc7
