### ISSUE TITLE
Add 'processing' indication when git actions are executing.

### ISSUE THREAD

**Issue by sminnee** [brotherbard/gitx#3]
Whilst you are running a rebase, pull, or push, there should be some indication that the operation is in progress, and that it has successfully executed.

**Comment by brotherbard** [comment]
At some point I need to make the git operations threaded, so I may wait till then to do something about this.

**Comment by sminnee** [comment]
Fair enough; I guess the thing is that right now it's really hard to tell whether the operation completed successfully.

**Comment by brotherbard** [comment]
If there is an error it will show a sheet with whatever git spits out for the error.

Another option would be to show a sheet every time, but that seems rather tedious. Also I can't show a progress indicator or have any other interaction because the git operations block the UI.

**Comment by sminnee** [comment]
Sounds like a challenge.  What about putting a "XXX completed succesfully" message in the status bar for a couple of seconds after the action completes?

**Comment by brotherbard** [comment]
That's a possibility.

**Comment by brotherbard** [comment]
There is now a sheet with a progress indicator for the various remote operations.
