### ISSUE TITLE
[PATCH] Allow setting a symlink as Git path 

### ISSUE THREAD

**Issue by koraktor** [brotherbard/gitx#32]
There's a problem with GitX when using Homebrew to install Git. Homebrew installs each version of a brew into a unique directory, e.g. `/usr/local/Cellar/git/1.7.2.1/` and symlinks its executables into `/usr/local/bin/`. GitX only saves the real path to the Git executable. After updating Git you have to update your GitX preferences or you will either use an outdated Git version or it will fail (when you cleanup the old version).
GitX should allow using a symlink to Git.

I have a small patch for this at koraktor/gitx@4fd0cf4ccd8511e2639629e9b22e952817bd8165.

**Comment by brotherbard** [comment]
Thanks, I'll add this when I do my next update.

**Comment by brotherbard** [comment]
I added this patch at SHA: caa6ed01f9e48f01c4f591467eac78d1b1d48905
