### ISSUE TITLE
GitX for Linux! GitX for Linux! GitX for Linux!

### ISSUE THREAD

**Issue by mariozaizar** [brotherbard/gitx#34]
GitX for Linux! please.

**Comment by apetresc** [comment]
There are many graphical Git clients for Linux. Look into Giggle, for example. GitX itself is heavily Cocoa-based, so "porting" it to Linux would involve rewriting the whole thing from scratch, at which point -- it's not really GitX anymore, is it?

**Comment by brotherbard** [comment]
There is also gitg http://trac.novowork.com/gitg/

**Comment by mariozaizar** [comment]
Yep, I've  already used that before, but nothing good as GitX, now I'm using Smartgit :/
