### ISSUE TITLE
thanks and request

### ISSUE THREAD

**Issue by insane-dreamer** [brotherbard/gitx#35]
Thank you for this experimental branch. It's great to see more features added.

A request: Add 'revert' as an option available to single commits.

(Also, cherry-pick is on the menu but doesn't seem to be available. Not implemented yet?)

**Comment by insane-dreamer** [comment]
PS. Ignore my comment on the cherry-pick; I discovered how it's used.

**Comment by brotherbard** [comment]
Glad you like it.
