### ISSUE TITLE
Line staging/unstaging doesn’t work

### ISSUE THREAD

**Issue by JanX2** [brotherbard/gitx#37]
It’s working fine in 0.7.1 but isn’t in “Experimental branch 7-5-2010”. Clicking the “Stage Line” button for a line in the diff causes an error message to appear.

**Comment by brotherbard** [comment]
It works for me. Do you have the context set to zero? Or changed any other setting related to diff in git config?

Does this patch fix it?
http://github.com/epall/gitx/commit/d5ed9efcb8b853012414c766e349cdd19de89b8e

**Comment by JanX2** [comment]
Indeed it does. I am really impressed now. :)

**Comment by brotherbard** [comment]
Well, it is someone else's patch, but since I can't reproduce the problem I had a hard time determining if it actually fixed the problem. You just confirmed it for me. Thanks!

It will now be in my next update.
