### ISSUE TITLE
No way of pushing all tracked branches to the given remote

### ISSUE THREAD

**Issue by sminnee** [brotherbard/gitx#4]
I'm having trouble working with multiple remotes.

In addition to my default remote, 'origin', I have another remote, 'prod', that tracks two branches, master and 0.1.

```
> git remote show prod
* remote prod
  URL: user@server:/var/www
  Tracked remote branches
    0.1 master
```

Now, if I run "git push prod", I will push both branches to the prod remote (which is not the default remote)

In the GitX UI, I appear to have two options:
- Push all synced branches to the default remote (in this case, 'origin')
- Push one branch to a corresponding branch on a another remote.

However, what I really want to be able to do is say "push all tracked branches to prod".  In particular, the current interface makes it too easy to accidenally push my local 'master' branch onto the remote '0.1' branch.  Which would be bad.

To give a bit of context, I used a remote called 'prod' to do deployment - there's a brief write-up here: http://minnee.geek.nz/deployment-using-git

**Comment by brotherbard** [comment]
> Push all synced branches to the default remote (in this case, 'origin')

Actually it will only push the branch you are viewing (in the branch pull down menu or the checked out branch if viewing All Branches). There is an error in the tooltip, the actual git command is "git push [remote] [branch]".

> However, what I really want to be able to do is say "push all tracked branches to prod".

What if I added a menu item to the top of each remote submenu called "All branches" or "All tracked branches" that would then do a "git push [remote]"?

**Comment by sminnee** [comment]
> What if I added a menu item to the top of each remote submenu called "All branches" or "All tracked branches" that would then do a "git push [remote]"?

That sounds good to me.  I guess "All tracked branches" would be more accurate?

**Comment by sminnee** [comment]
I guess my only gripe is that it seems like pushing all tracked branches would be by far the most common use-case, and so it would make more sense to have fewer clicks for that option.  The menu selection options could then be:
- Push -> origin (all tracked branches)
- Push -> one branch -> origin -> master

Of course, my assumption that "pushing all tracked branches would be by far the most common use-case" could be wrong...

**Comment by brotherbard** [comment]
I'll think on this some more.

**Comment by brotherbard** [comment]
I added tracking remote items to the drop down menu for Fetch, Pull and Push in 2cd7a4a7.
