### ISSUE TITLE
Deleting a detached head makes the repository unusable

### ISSUE THREAD

**Issue by felixyz** [brotherbard/gitx#41]
I (stupidly) deleted a detached head, and after that any attempt to run git commands on the repo (in gitx or from command line) only evoked this message: 
"fatal: Not a git repository (or any of the parent directories)"

The problem was that the HEAD file was deleted from the .git folder. I copied ORIG_HEAD to HEAD, and then I could check out a branch and get back to where I was, but this was a pretty jarring experience.

I suggest that it either be impossible to delete a detached head, or that there is an ultra-clear warning describing what will happen.

**Comment by brotherbard** [comment]
This should be fixed in SHA: 5ddbcd18ef1494bb7cd00189d846e580e9d1d64a
