### ISSUE TITLE
Newest experimental release won't start

### ISSUE THREAD

**Issue by billturner** [brotherbard/gitx#47]
When starting gitx at the command line from within a repository, the following error shows up:

```
gitx(171,0x7fff702dac20) malloc: reference count underflow for 0x2000a1660, break on auto_refcount_underflow_error to debug.
```

And it hangs at this point.

**Comment by billturner** [comment]
The exact release is GitX Sep-12-2010.zip Experimental branch (release 3.0.1)

**Comment by brotherbard** [comment]
What OS are you running?

**Comment by billturner** [comment]
OS: 10.6.4

Local git version: 1.7.1

**Comment by franciscoj** [comment]
I had to start the application double clicking the icon and then do "Enable Terminal Usage..." again in the GitX menu before I could use the terminal.

**Comment by billturner** [comment]
Thanks franciscoj! 

That will now allow it to launch (from the command line in a repository), but the error still appears. It now opens completely instead of hanging.

**Comment by franciscoj** [comment]
I'm using OSX 10.6.4 with git 1.7.1.1 installed using homebrew and I don't get the error once I've the enabled terminal usage.

**Comment by heipei** [comment]
Hm, one question: Did you put the new experimental build into /Applications? The 'gitx' command run by the user is just a symlink to the gitx-binary in the GitX.app subfolder.

The only thing triggering this bug that comes to mind is using differing versions of 'gitx' and 'GitX.app', strange as that may sound ;)

**Comment by franciscoj** [comment]
Yes, I put it into my Applications folder before I ran it.
