### ISSUE TITLE
Option to push a new branch to a remote

### ISSUE THREAD

**Issue by sminnee** [brotherbard/gitx#5]
When you create a remote, it appears push the current branch to that remote.  It would be nice if there was a way of pushing additional branches to the remote.

The command that I'm thinking of would be one of the form

```
git push (remote) (branch):(branch)
```

Perhaps the "push" menu can include local branches that don't exist on the given remote in the push menu, labelled appropriately?  Something like:
- Push
  - prod
  - master
  - Add '0.1' to 'prod'

Alternatively, we could have an extra level of menu items:
- Push
  - prod
  - master
  - Add a branch
    - 0.1

**Comment by brotherbard** [comment]
I think this is slightly more advanced than what the toolbar menu's can support. I plan on working on the [sidebar](http://wiki.github.com/pieter/gitx/sidebar-interface-mockup) part of the project sometime next month and I think that there will be better places to do management of remotes in that UI. 

There we should be able to do what you are asking.

**Comment by sminnee** [comment]
Fair enough; those menus are getting kind of full.

**Comment by brotherbard** [comment]
This works now. In the contextual menu for a branch you can select any remote to push to.
