### ISSUE TITLE
Rebase creates a detached head

### ISSUE THREAD

**Issue by thomasroefer** [brotherbard/gitx#53]
Rebasing currently requires three steps where other tools only require one. When pressing "Rebase", a detached head is created. Then, the label of the rebased branch has to be dragged to that commit. Finally, the rebased branch has to be checked out again. It would be better when pressing "Rebase" would do all at once, since the three step method is rather error-prone.

**Comment by brotherbard** [comment]
That's a bug, I'll look into what's causing it.

**Comment by brotherbard** [comment]
This is fixed in SHA: 6f83f2382cb4e02b205b19d7bb0ba09b505f4ded
