### ISSUE TITLE
Creating a local branch from a remote branch creates a detached head

### ISSUE THREAD

**Issue by thomasroefer** [brotherbard/gitx#54]
Creating a local branch from a remote branch currently requires three steps where other tools only require one. The only method I found is to checkout the remote branch, which results in a detached head. Afterwards, a new local branch has to be created from that detached head. Here, one has to be careful to use the same name as for the remote branch. Afterwards, the new branch can be checked out.

**Comment by heipei** [comment]
Invalid. Nathan's branch allows this all in one step.

**Comment by thomasroefer** [comment]
How? Or isn't "experimental" not Nathan's branch?

**Comment by heipei** [comment]
I can just right-click on a remote branch and select 'Create Branch'. A window pops up, asking the name for the new branch and whether I want to check it out right away.

**Comment by thomasroefer** [comment]
You are right, that works. I expected creating a new branch on the server behind that menu entry, especially since it asks for a branch name. I would suggest to use the name of the remote branch as default value in the dialog asking for the name.

**Comment by brotherbard** [comment]
When you create a local branch by right-clicking on a remote branch (in the sidebar or in the history view) it will be set as tracking branch for that remote branch.

Using the name in the dialog is a good idea.

**Comment by brotherbard** [comment]
The Create Branch sheet will now pre-fill the branch name if creating a branch on a remote branch. SHA: e388434a493b74386fbefdbab0f9c57f51004fe2

Also the contextual menu for a remote branch will now say "Create branch that tracks origin/topic…" so that it is discoverable that the branch created is a tracking branch. SHA: 929f9fc0f59389f422c280333dbdd41b2844b42e
