### ISSUE TITLE
Pull master from origin; origin/master not moved.

### ISSUE THREAD

**Issue by sminnee** [brotherbard/gitx#6]
Test scenario:
- Another developer pushes an item to the master branch on origin
- I select pull -> origin -> master in GitX
- _First bug:_ The screen didn't refresh, so I pressed Command-R.  Does your previous fix need to be applied to pull and push as well?
- _Second bug:_ Although the new commit has been pulled in, and master has been moved to the new commit, origin/master is still sitting at its old point.

Going to the command-line and running "git pull" fixes this.

**Comment by sminnee** [comment]
Note that the 2nd bug appears to happen with push as well.  The first one _may_, I can't test it at this stage.

**Comment by brotherbard** [comment]
Hmm, it should have been for all the commands. I will have to look at it later.

**Comment by brotherbard** [comment]
This is fixed in 946d4964
