### ISSUE TITLE
Error using gitx command-line.

### ISSUE THREAD

**Issue by adamv** [brotherbard/gitx#63]
With version Version 0.7.1 (v0.7.1-183-g549f2c1): http://gist.github.com/595729

Let me know what other info I can provide.

(I can tarball up the repo and upload it somewhere if you want to test against it.)

**Comment by brotherbard** [comment]
You probably need to re-enable terminal usage. It's in the GitX app menu.

**Comment by adamv** [comment]
gitx is working fine in all the other repos I've tested it in.

**Comment by brotherbard** [comment]
What does 'gitx -v' print out?

**Comment by adamv** [comment]
```
[~/buggy] (work)
$ gitx -v
This is GitX version 0.7.1
Using git found at /usr/local/bin/git, version 1.7.3
```

**Comment by brotherbard** [comment]
Yes, re-do the 'Enable terminal usage' again. I'm guessing you placed the latest GitX.app in a different place then before (alternatively you could replace the old version with the new version on disk).

The old gitx version would crash if run from outside a git repository but the current version won't, instead GitX.app will show a message stating the directory is not a git repository.

**Comment by adamv** [comment]
Re-enabled. Within a git repo folder I still get: http://gist.github.com/596027

**Comment by brotherbard** [comment]
Sorry, I missed the patch number in your first message. I have a newer release (commit 59c4983) out that has updated the gitx cli tool. It's in the downloads section. The one you are running is from my July release (commit 549f2c1).

```
$ gitx -v
GitX version 0.7.1 (v0.7.1-233-g59c4983)
Using git found at /usr/bin/git, version 1.7.2.1
```

If you already have my latest release then OS X is running the old one still. From the Dock right click on the GitX.app icon and choose Options->Show in Finder and either trash it or compress it. Then it won't run anymore. Then run GitX.app from the Finder and do 'Enable terminal usage' again and then it should work.

**Comment by adamv** [comment]
I was still having this problem with the newest download, but I blew away the problem repo and re-got. No longer having a problem in that repo, and no longer have a reproducible case, so closing.
