### ISSUE TITLE
Window keeps disappearing after failing to discard a hunk

### ISSUE THREAD

**Issue by sminnee** [brotherbard/gitx#7]
This is a bit of a weird one.

Test case:
- Attempt to discard a hunk of a changed file, that fails because git says "patch does not apply".
- GitX window is hidden, and just the error dialog box is shown.
- Press OK in the dialog
- Click on GitX in the dock, the GitX window appears
- Click anywhere on the GitX window, it disappears.

The only way to get out of this state is to re-start GitX.

**Comment by brotherbard** [comment]
This is fixed in 10a0cb59
