### ISSUE TITLE
MacVim Raises Error When Disconnecting External Display

### ISSUE THREAD

**Issue by jherdman** [brotherbard/gitx#71]
When disconnecting my external display, the following error is printed in my prompt:

<pre><code>Sun Oct 17 14:47:01 amadeus.local MacVim[19731] <Error>: kCGErrorIllegalArgument: CGSShapeWindow
Sun Oct 17 14:47:01 amadeus.local MacVim[19731] <Error>: kCGErrorFailure: Set a breakpoint @ CGErrorBreakpoint() to catch errors as they are logged.</code></pre>

**Comment by brotherbard** [comment]
This is related to GitX?

**Comment by jherdman** [comment]
Ugh... sorry man. I got my tabs mixed up. Closing...
