### ISSUE TITLE
'Discard hunk' in commit view appears to never work

### ISSUE THREAD

**Issue by sminnee** [brotherbard/gitx#8]
The 'Discard' button that appears at the top of each hunk in the commit view appears to never work.  I have seen cases where GitX 0.7.1 will discard the hunk correctly but your GitX fails, with the 'git could not apply patch' error.

**Comment by brotherbard** [comment]
Were you trying to discard after a merge (or other) conflict or when staging normal changes? Discarding hunks in normal commits works for me but discarding when there is a conflict does not (and causes the disappearing window you reported in a different issue).

GitX does not currently support conflict changes (these start with "<<<<<<< HEAD").

For now I'll look into disabling the discard/stage buttons until conflict resolution is added.

**Comment by sminnee** [comment]
Hrm.  I've had very little success using _any_ of the partial staging options in your GitX build.

Is there any way that I can get you diagnostic information?

**Comment by tiennou** [comment]
Damn, I just struggled like crazy trying to understand why partial staging was broken for me too. In fact, it amounted to the "Context" slider in the commit view: at 0, partial staging fails every time. Move it up a notch, and it works ! Now I'm a happy GitX user again.

**Comment by sminnee** [comment]
Yeah - I noticed the Context slider issue as well.

I suspect that the solution may be to generate patches with more context for the purposes of applying lines.  The context slider should only affect the view, not the behind-the-scenes patch generation.

**Comment by ghost** [comment]
I have similar problems: I was not able to undo a local commit by even unstage or discard. Further more I was searchung for a soft-reset, to avoid pushing my last, "useless" commit. 
Any ideas?

**Comment by brotherbard** [comment]
This should be fixed in SHA: c077f234ea0817130f804c18769e633371db2fce
